### ISSUE TITLE
module 'doodad.easy_launch.config' has no attribute 'DIR_AND_MOUNT_POINT_MAPPINGS'

### ISSUE THREAD

**Issue by bithgz** [Neo-X/SMiRL_Code#2]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
SMiRL not installed
  File "scripts/dqn_smirl.py", line 270, in <module>
LLM not installed
    meta_threads=settings['meta_sim_threads'])
  File "/home/hu/2021/smirl3/SMiRL_Code-master/util/tuneParams.py", line 62, in run_sweep
    pool.map(run_exp, exp_args)
  File "/home/hu/anaconda3/envs/smirl3/lib/python3.5/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/hu/anaconda3/envs/smirl3/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: module 'doodad.easy_launch.config' has no attribute 'DIR_AND_MOUNT_POINT_MAPPINGS'

**Comment by Neo-X** [comment]
I forgot to add this to the default config.py file in the doodad code. I updated that now.
https://github.com/Neo-X/doodad/commit/174e709c991c5d06712dfced888c6815fb719fd5
Please update and try again.

**Comment by bithgz** [comment]
> I forgot to add this to the default config.py file in the doodad code. I updated that now.
> [Neo-X/doodad@174e709](https://github.com/Neo-X/doodad/commit/174e709c991c5d06712dfced888c6815fb719fd5)
> Please update and try again.



May you give a configuration  for your successful operation on other computers?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/dqn_smirl.py", line 268, in <module>
    meta_threads=settings['meta_sim_threads'])
  File "/home/hu/2021/smirl/SMiRL/util/tuneParams.py", line 62, in run_sweep
    pool.map(run_exp, exp_args)
  File "/home/hu/anaconda3/envs/smirl/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/hu/anaconda3/envs/smirl/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/gberseth/.mujoco'

**Comment by bithgz** [comment]
Have you ever configured it successfully with this git you uploaded in other computers? I have encountered too many problems.
